### ISSUE TITLE
Classification Cartography 

### ISSUE THREAD

**Issue by brigsz** [agrc/land-mobile-radio#18]
more color variation at higher levels

**Comment by stdavis** [comment]
Here's my best stab at it. If this isn't good then we should have a professional like @ZachBeck work on it.

Before:
![image](https://cloud.githubusercontent.com/assets/1326248/6271871/083d2076-b821-11e4-883d-bcf21690e23e.png)

After:
![image](https://cloud.githubusercontent.com/assets/1326248/6271876/0f7d6ad0-b821-11e4-9899-0c2da71ee99a.png)

**Comment by stdavis** [comment]
Couldn't resist one more try:
![image](https://cloud.githubusercontent.com/assets/1326248/6272401/83310448-b824-11e4-9353-6f8f602107f1.png)

**Comment by brigsz** [comment]
Stop before you hurt yourself!
